const productos = [
  {
    id: 1,
    precio: 52.0,
    nombre: "Chicken Veggie Salad",
    descripcion: "With Cheese souse",
    cantidad: 0,
    imagen: "./img/comida-rapida-casera.jpg",
  },
  {
    id: 2,
    categoria: "Dinner",
    precio: 23.0,
    nombre: "Mutton Curry",
    descripcion: "With bastami rice",
    cantidad: 0,
    imagen: "./img/vegetales.jpg",
  },
  {
    id: 3,
    precio: 21.0,
    nombre: "French fry",
    descripcion: "With beef bacon",
    cantidad: 0,
    imagen: "./img/desayuno.jpg",
  },
  {
    id: 4,
    categoria: "Fast Food",
    precio: 20.0,
    nombre: "Drinks",
    descripcion: "With ....",
    cantidad: 0,
    imagen: "./img/bebidas.jpg",
  },
  {
    id: 5,
    precio: 21.0,
    nombre: "French fry",
    descripcion: "With beef bacon",
    cantidad: 0,
    imagen: "./img/desayuno.jpg",
  },
  {
    id: 6,
    precio: 21.0,
    nombre: "French fry",
    descripcion: "With beef bacon",
    cantidad: 0,
    imagen: "./img/cena2.jpg",
  },
  {
    id: 7,
    precio: 21.0,
    nombre: "French fry",
    descripcion: "With beef bacon",
    cantidad: 0,
    imagen: "./img/desayuno.jpg",
  },
  {
    id: 8,
    precio: 27.0,
    nombre: "French fry",
    descripcion: "With beef bacon",
    cantidad: 0,
    imagen: "./img/desayuno.jpg",
  },
];
